apiVersion: batch/v1

kind: CronJob

metadata:

  name: synaptiqtest1

spec:

  schedule: "*/30 * * * *"

  jobTemplate:

    spec:

      backoffLimit: 1
      template:

        spec:

          containers:

          - name: synaptiqtest1

            image: harbor.tanzu.local/library/synaptiq-python:1.0

            imagePullPolicy: IfNotPresent

            command:

            - /bin/sh

            - -c

            - python /app/app.py

          restartPolicy: OnFailure
